site_name: Brackets Documentation
site_url: https://drarig29.github.io/brackets-docs
repo_url: https://github.com/Drarig29/brackets-docs
repo_name: brackets-docs
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)" 
      primary: blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      primary: blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - "Welcome": "index.md"
  - "Getting Started": "getting-started.md"
  - "User Guide":
    - "Glossary": "user-guide/glossary.md"
    - "Seeding": "user-guide/seeding.md"
    - "Ordering": "user-guide/ordering.md"
    - "Storage": "user-guide/storage.md"
  - "FAQ": "faq.md"
  - "Demos":
    - "Angular": "https://stackblitz.com/edit/angular-ivy-bhv3yu"
    - "React": "https://replit.com/@Drarig29/React-and-brackets-viewerjs#src/App.js"
    - "Toornament API": "https://replit.com/@Drarig29/Toornament-and-brackets-viewerjs#src/App.js"
  - "Reference":
    - "brackets-manager.js": "reference/manager"
    - "brackets-viewer.js": "reference/viewer"
    - "brackets-model": "reference/model"
  - "About": "about.md"
extra_css:
  - css/style.css
extra_javascript:
  - js/star-history.js
  - js/load-charts.js
markdown_extensions:
  - admonition
  - abbr
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true