site_name: Brackets Documentation
theme:
  name: material
markdown_extensions:
  - admonition
  - abbr
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true