name: Build

env:
  GIT_AUTHOR_EMAIL: "brackets-docs-update[bot]@drarig29.github.io"
  GIT_AUTHOR_NAME: "brackets-docs-update"

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy the docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set git user
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
      - name: Update versions
        run: |
          make update
          git commit --all -m "Update package versions"
          git push

      - name: Build and deploy
        uses: ./ # Uses an action in the root directory
