on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build my documentation
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with mkdocs
        uses: ./ # Uses an action in the root directory